import dataset from"../data/codes.json";import{Resolver}from"./resolver";
export default function Home(){const districts=dataset.codes.filter(item=>item.entityType==="district");return <main><header><a className="brand" href="https://digitalghana.dev"><i>GC</i><span>Digital Ghana<br/><b>GhanaCodes</b></span></a><nav><a href="#resolver">Resolver</a><a href="#namespaces">Namespaces</a><a href="https://github.com/stanleyHayes/ghanacodes">GitHub</a></nav></header>
<section className="hero"><p className="eyebrow">Interoperability · without name matching</p><h1>Codes should join data.<br/><em>Not distort it.</em></h1><div className="hero-bottom"><p>Resolve Ghanaian region and district identifiers against an explicit namespace, effective date, dataset version, and source. Ambiguity stays visible.</p><dl><div><dt>261</dt><dd>district codes</dd></div><div><dt>16</dt><dd>regions</dd></div><div><dt>3</dt><dd>namespaces</dd></div></dl></div></section>
<section className="try" id="resolver"><div><p className="eyebrow">Exact resolver</p><h2>Ask with context.</h2><p>A bare value like <code>03</code> is not enough. Select the code system first, then GhanaCodes resolves only within that namespace and effective version.</p></div><Resolver codes={dataset.codes}/></section>
<section className="namespaces" id="namespaces"><div className="section-head"><p className="eyebrow">Dataset {dataset.version}</p><h2>Three declared namespaces.<br/>One identity underneath.</h2></div><ol>{dataset.namespaces.map((namespace,index)=><li key={namespace.id}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{namespace.name}</h3><code>{namespace.id}</code></div><p>{namespace.entityType}<br/><b>{namespace.authority}</b></p></li>)}</ol></section>
<section className="crosswalk"><div><p className="eyebrow">Crosswalk, do not guess</p><h2><span>03</span><i>→</i><span>GAR</span></h2><p>Both values resolve to <code>geo:region:03</code>. If a target namespace has multiple valid candidates, the API returns all candidates with an <b>ambiguous</b> status.</p></div><pre>{`GET /v1/crosswalk\n  ?fromNamespace=gss-phc-2021-region\n  &code=03\n  &toNamespace=gss-phc-2021-region-abbreviation\n\n{\n  "status": "resolved",\n  "candidates": [{ "code": "GAR" }]\n}`}</pre></section>
<section className="register"><div><p className="eyebrow">Official register sample</p><h2>District codes</h2><p>The complete 261-code register is available through the API. Names here retain the 2021 GSS source version.</p></div><div className="table">{districts.slice(0,14).map(item=><div key={item.code}><code>{item.code}</code><strong>{item.name}</strong><span>Region {item.regionCode}</span></div>)}</div></section>
<section className="source"><p className="eyebrow">Provenance</p><p>Generated reproducibly from the Ghana Statistical Service 2021 PHC Field Officer's Manual using a pinned SHA-256. The official PDF is linked, not redistributed. The Ministry MMDA directory is a review aid—not an unreviewed canonical import.</p><a href="https://github.com/stanleyHayes/ghanacodes/blob/main/docs/governance/source-register.json">Inspect sources and decisions ↗</a></section>
<footer><strong>GhanaCodes</strong><span>A Digital Ghana public-infrastructure project.</span><a href="mailto:hello@digitalghana.dev">Report a code conflict</a></footer></main>}
